c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

cuda_compiler:
  - cuda-nvcc

cuda11_compiler:
  - nvcc

sysroot_version:
  - "2.17"

cmake_version:
  - ">=3.26.4"

# Match with dependencies.yaml, and keep in sync with the conda-forge pinning
proj:
  - "9.3.0"
